version: '3'
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /c/mysql/data:/var/lib/mysql
