version: "3"
services:
  webapp:
    build: ./webapp # 根据指定目录下的Dockerfile构建镜像
    links:
      - webserver # 允许一个容器能够访问另一个容器，并在它们之间建立网络连接
    ports:
      - "4534:4534"
  webserver:
    build: ./webserver # 根据指定目录下的Dockerfile构建镜像
    expose:
      - "3000" # 暴露容器给link到当前容器的容器使用
